### ISSUE TITLE
Use NPM `ethpm-spec` package properly

### ISSUE THREAD

**Issue by gnidan** [ethpm/ethpm.js#1]
Currently ethpm/ethpm-spec is missing from this repo because the right approach is likely to keep https://www.npmjs.com/package/ethpm-spec up to date and just define that as a dependency.

The `json2ts` stuff can likely also be moved over there, to allow people to `import * as schema from "ethpm-spec"` and get types. Or we could make `@types/ethpm-spec`.

**Comment by njgheorghita** [comment]
sorted in #28
